services:
  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    container_name: go_study
    volumes:
      - type: bind
        source: ./go/src
        target: /app
    environment:
      - SWITCHBOT_TOKEN=${SWITCHBOT_TOKEN}
      - SWITCHBOT_HUB2_ID=${SWITCHBOT_HUB2_ID}
      - SWITCHBOT_PLUG_MINI_MAIN_ID=${SWITCHBOT_PLUG_MINI_MAIN_ID}
      - SWITCHBOT_PLUG_MINI_SECOND_ID=${SWITCHBOT_PLUG_MINI_SECOND_ID}

  mysql:
    build: ./sql/
    volumes:
      - type: bind
        source: ./sql/initdb.d
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./sql/db
        target: /var/lib/mysql
    image: mysqlapp
    container_name: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
