services:
  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    container_name: go_study
    volumes:
      - type: bind
        source: ./go/src
        target: /app
    environment:
      - SWITCHBOT_TOKEN=${SWITCHBOT_TOKEN}
      - SWITCHBOT_SECRET=${SWITCHBOT_SECRET}
      - SWITCHBOT_HUB2_ID=${SWITCHBOT_HUB2_ID}
      - SWITCHBOT_PLUG_MINI_MAIN_ID=${SWITCHBOT_PLUG_MINI_MAIN_ID}
      - SWITCHBOT_PLUG_MINI_SECOND_ID=${SWITCHBOT_PLUG_MINI_SECOND_ID}
      - OPEN_WEATHER_API=${OPEN_WEATHER_API}

  prometheus:
    image: prom/prometheus:latest
    container_name: ${PROJECT_NAME}_prometheus
    ports:
     - '9090:9090'
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yaml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: ./data
        target: /etc/prometheus/data
