services:
  exporter:
    build:
      context: ./exporter
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./exporter/src
        target: /app
