services:
  exporter:
    build:
      context: ./exporter
      dockerfile: Dockerfile
    container_name: exporter
    ports:
      - "2112:2112"
    environment:
      - SWITCHBOT_TOKEN=${SWITCHBOT_TOKEN}
      - SWITCHBOT_HUB2_ID=${SWITCHBOT_HUB2_ID}
      - SWITCHBOT_PLUG_MINI_MAIN_ID=${SWITCHBOT_PLUG_MINI_MAIN_ID}
      - SWITCHBOT_PLUG_MINI_SECOND_ID=${SWITCHBOT_PLUG_MINI_SECOND_ID}
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
     - '9090:9090'
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yaml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: ./data
        target: /etc/prometheus/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./grafana/provisioning
        target: /etc/grafana/provisioning
      - type: bind
        source: ./grafana/dashboards
        target: /var/lib/grafana/dashboards
      
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
